INSERT INTO assessment_dev.users (name, email)
VALUES ('Vishnu', 'vishnu@example.com');

SELECT * FROM assessment_dev.users;

SELECT column_name
FROM information_schema.columns
WHERE table_schema = 'assessment_dev'
AND table_name = 'users';
commit



select * from roles;

select * from user_role_map
INSERT INTO assessment_dev.user_role_map (user_id, role_id) VALUES (1, 1);
ALTER TABLE assessment_dev.roles
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO assessment_dev.roles (name, description, valid)
VALUES ('PLATFORM_ADMIN', 'Platform administrator with full access', true);

INSERT INTO assessment_dev.roles (name, description, valid)
VALUES ('COMPANY_ADMIN', 'Company administrator who manages assessments', true);

INSERT INTO assessment_dev.roles (name, description, valid)
VALUES ('CANDIDATE', 'Candidate who takes assessments', true);